In [2]:
import pandas as pd

## Aşağıdaki veri seti tüm sorular için kullanılacaktır

In [6]:
veri = {
    "isim": ["Ali", "Ayşe", "Mehmet", "Zeynep", "Ahmet", "Elif"],
    "yas": [25, 30, 28, 35, 22, 27],
    "sehir": ["Ankara", "İstanbul", "Ankara", "İzmir", "Bursa", "İstanbul"],
    "maas": [5000, 7000, 6000, 8000, 4500, 6500]
}

df = pd.DataFrame(veri)

In [11]:
df

     isim  yas     sehir  maas
0     Ali   25    Ankara  5000
1    Ayşe   30  İstanbul  7000
2  Mehmet   28    Ankara  6000
3  Zeynep   35     İzmir  8000
4   Ahmet   22     Bursa  4500
5    Elif   27  İstanbul  6500

### Soru 1
#### DataFrame'in ilk 3 satırını gösterin

In [15]:
df.head(3)

     isim  yas     sehir  maas
0     Ali   25    Ankara  5000
1    Ayşe   30  İstanbul  7000
2  Mehmet   28    Ankara  6000

### Soru 2
#### DataFrame'deki sütun isimlerini ekrana yazdırın

In [36]:
df.columns

Index(['isim', 'yas', 'sehir', 'maas'], dtype='object')

### Soru 3
#### Sadece "isim" sütununu seçin

In [39]:
df["isim"]

0       Ali
1      Ayşe
2    Mehmet
3    Zeynep
4     Ahmet
5      Elif
Name: isim, dtype: object

### Soru 4
#### Sadece "isim" ve "maas" sütunlarını birlikte gösterin

In [43]:
df[["isim" , "maas"]]

     isim  maas
0     Ali  5000
1    Ayşe  7000
2  Mehmet  6000
3  Zeynep  8000
4   Ahmet  4500
5    Elif  6500

### Soru 5
#### Yaşı 28'den büyük olan kişileri filtreleyin

In [33]:
df[df["yas"] > 28]

     isim  yas     sehir  maas
1    Ayşe   30  İstanbul  7000
3  Zeynep   35     İzmir  8000

### Soru 6
#### Maaşı 6000'den büyük olan kişilerin sadece isim ve maaş bilgilerini gösterin

In [48]:
df[df["maas"] > 6000][["isim", "maas"]]

     isim  maas
1    Ayşe  7000
3  Zeynep  8000
5    Elif  6500

### Soru 7
#### Maaşa göre küçükten büyüğe sıralayın

In [54]:
df.sort_values("maas")

     isim  yas     sehir  maas
4   Ahmet   22     Bursa  4500
0     Ali   25    Ankara  5000
2  Mehmet   28    Ankara  6000
5    Elif   27  İstanbul  6500
1    Ayşe   30  İstanbul  7000
3  Zeynep   35     İzmir  8000

### Soru 8
#### Maaşa göre büyükten küçüğe sıralayın

In [57]:
df.sort_values("maas", ascending=False)

     isim  yas     sehir  maas
3  Zeynep   35     İzmir  8000
1    Ayşe   30  İstanbul  7000
5    Elif   27  İstanbul  6500
2  Mehmet   28    Ankara  6000
0     Ali   25    Ankara  5000
4   Ahmet   22     Bursa  4500

### Soru 9
#### Şehirlere göre gruplama yapın ve her şehir için ortalama maaşı hesaplayın

In [60]:
df.groupby("sehir")["maas"].mean()

sehir
Ankara      5500.0
Bursa       4500.0
İstanbul    6750.0
İzmir       8000.0
Name: maas, dtype: float64

### Soru 10
#### "yillik_maas" adında yeni bir sütun oluşturun
#### Bu sütun maaşın 12 ile çarpılması ile oluşturulacaktır

In [63]:
df["yillik_maas"] = df["maas"] * 12

In [65]:
df

     isim  yas     sehir  maas  yillik_maas
0     Ali   25    Ankara  5000        60000
1    Ayşe   30  İstanbul  7000        84000
2  Mehmet   28    Ankara  6000        72000
3  Zeynep   35     İzmir  8000        96000
4   Ahmet   22     Bursa  4500        54000
5    Elif   27  İstanbul  6500        78000